name: Déploiement - Docker Hub

on:
  workflow_run:
    workflows: ["Qualité - SonarCloud"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Docker Build & Push
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        run: |
          cd back
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-back .
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back

      - name: Build and push frontend
        run: |
          cd front
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-front .
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-front

      - name: Clean up local Docker images
        run: |
          docker rmi ${{ secrets.DOCKER_USERNAME }}/bobapp-back || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/bobapp-front || true

# Ce workflow est exécuté UNIQUEMENT après l’analyse SonarCloud si tout est OK.
# Il build et publie les images Docker du frontend et du backend sur Docker Hub.